// ============================================================
//  js/config.js — YOUR PERSONAL SETTINGS
//  ✅ Edit this file to update:
//     - UI labels (English & Chinese)
//     - Your name, bio, skills, social links
//
//  Do NOT edit js/data.js — it is auto-generated by build.py
// ============================================================

window.SITE_DATA = {

  // ==========================================================
  // UI LABELS — edit if you want different button/label text
  // ==========================================================
  i18n: {
    en: {
      nav_home:           "Home",
      nav_research:       "Research",
      nav_about:          "About Me",
      nav_blogs:          "Blogs",
      latest_posts:       "Latest Posts",
      research_title:     "Research",
      blogs_title:        "Blogs",
      about_title:        "About Me",
      read_more:          "Read →",
      back:               "← Back",
      search_title:       "Search",
      search_placeholder: "Type keywords...",
      no_results:         "No results found.",
      hero_greeting:      "Welcome, Space Traveler!",
      hero_subtitle:      "Exploring the cosmos of knowledge",
      about_badge:        "ONLINE",
      tag_research:       "RESEARCH",
      tag_blog:           "BLOG",
      posted_on:          "Posted on",
      lang_btn:           "EN / 中",
      theme_day:          "☀",
      theme_night:        "☾",
    },
    zh: {
      nav_home:           "主页",
      nav_research:       "研究",
      nav_about:          "关于我",
      nav_blogs:          "博客",
      latest_posts:       "最新发布",
      research_title:     "研究",
      blogs_title:        "博客",
      about_title:        "关于我",
      read_more:          "阅读全文 →",
      back:               "← 返回",
      search_title:       "搜索",
      search_placeholder: "输入关键词...",
      no_results:         "没有找到相关内容。",
      hero_greeting:      "欢迎，太空旅行者！",
      hero_subtitle:      "探索知识的宇宙",
      about_badge:        "在线",
      tag_research:       "研究",
      tag_blog:           "博客",
      posted_on:          "发布于",
      lang_btn:           "中 / EN",
      theme_day:          "☀",
      theme_night:        "☾",
    }
  },

  // ==========================================================
  // ABOUT ME — edit everything here
  // ==========================================================
  about: {
    // Your display name
    name:       "Your Name",
    name_zh:    "你的名字",

    // One-line tagline shown below your name
    tagline:    "Researcher · Developer · Explorer",
    tagline_zh: "研究员 · 开发者 · 探索者",

    // Avatar: put your photo in images/ and set path e.g. "images/avatar.jpg"
    // Leave "" to show the emoji placeholder
    avatar:       "",
    avatar_emoji: "👨‍🚀",

    // Bio — use \n for a new paragraph
    bio: {
      en: `Hello! I'm a researcher and developer passionate about the intersection of science, technology, and creativity.\n\nFeel free to reach out — let's explore the cosmos together!`,
      zh: `你好！我是一名热爱科学、技术与创意交叉领域的研究者和开发者。\n\n欢迎联系我，让我们一起探索宇宙！`
    },

    // Skill bars — level is 0–100
    skills: [
      { label: "Research",      label_zh: "科研",     level: 85 },
      { label: "Programming",   label_zh: "编程",     level: 80 },
      { label: "Writing",       label_zh: "写作",     level: 75 },
      { label: "Data Analysis", label_zh: "数据分析", level: 70 },
    ],

    // Social / contact links
    socials: [
      { label: "GitHub",    url: "https://github.com/yourusername" },
      { label: "Twitter/X", url: "https://twitter.com/yourusername" },
      { label: "Email",     url: "mailto:you@example.com" },
    ]
  }

};
