// ============================================================
//  js/data.js — AUTO-GENERATED by build.py
//  Last built: 2026-03-22 09:45
//
//  ⚠  DO NOT edit this file directly.
//     Edit your posts in:  posts/research/*.md
//                          posts/blogs/*.md
//     Edit personal info in: js/config.js
//     Then run:  python build.py
// ============================================================

// ============================================================
//  js/config.js — YOUR PERSONAL SETTINGS
//  ✅ Edit this file to update:
//     - UI labels (English & Chinese)
//     - Your name, bio, skills, social links
//
//  Do NOT edit js/data.js — it is auto-generated by build.py
// ============================================================

window.SITE_DATA = {

  // ==========================================================
  // UI LABELS — edit if you want different button/label text
  // ==========================================================
  i18n: {
    en: {
      nav_home:           "Home",
      nav_research:       "Research",
      nav_about:          "About Me",
      nav_blogs:          "Blogs",
      latest_posts:       "Latest Posts",
      research_title:     "Research",
      blogs_title:        "Blogs",
      about_title:        "About Me",
      read_more:          "Read →",
      back:               "← Back",
      search_title:       "Search",
      search_placeholder: "Type keywords...",
      no_results:         "No results found.",
      hero_greeting:      "Welcome, Space Traveler!",
      hero_subtitle:      "Exploring the cosmos of knowledge",
      about_badge:        "ONLINE",
      tag_research:       "RESEARCH",
      tag_blog:           "BLOG",
      posted_on:          "Posted on",
      lang_btn:           "EN / 中",
      theme_day:          "☀",
      theme_night:        "☾",
    },
    zh: {
      nav_home:           "主页",
      nav_research:       "研究",
      nav_about:          "关于我",
      nav_blogs:          "博客",
      latest_posts:       "最新发布",
      research_title:     "研究",
      blogs_title:        "博客",
      about_title:        "关于我",
      read_more:          "阅读全文 →",
      back:               "← 返回",
      search_title:       "搜索",
      search_placeholder: "输入关键词...",
      no_results:         "没有找到相关内容。",
      hero_greeting:      "欢迎，太空旅行者！",
      hero_subtitle:      "探索知识的宇宙",
      about_badge:        "在线",
      tag_research:       "研究",
      tag_blog:           "博客",
      posted_on:          "发布于",
      lang_btn:           "中 / EN",
      theme_day:          "☀",
      theme_night:        "☾",
    }
  },

  // ==========================================================
  // ABOUT ME — edit everything here
  // ==========================================================
  about: {
    // Your display name
    name:       "Your Name",
    name_zh:    "你的名字",

    // One-line tagline shown below your name
    tagline:    "Researcher · Developer · Explorer",
    tagline_zh: "研究员 · 开发者 · 探索者",

    // Avatar: put your photo in images/ and set path e.g. "images/avatar.jpg"
    // Leave "" to show the emoji placeholder
    avatar:       "",
    avatar_emoji: "👨‍🚀",

    // Bio — use \n for a new paragraph
    bio: {
      en: `Hello! I'm a researcher and developer passionate about the intersection of science, technology, and creativity.\n\nFeel free to reach out — let's explore the cosmos together!`,
      zh: `你好！我是一名热爱科学、技术与创意交叉领域的研究者和开发者。\n\n欢迎联系我，让我们一起探索宇宙！`
    },

    // Skill bars — level is 0–100
    skills: [
      { label: "Research",      label_zh: "科研",     level: 85 },
      { label: "Programming",   label_zh: "编程",     level: 80 },
      { label: "Writing",       label_zh: "写作",     level: 75 },
      { label: "Data Analysis", label_zh: "数据分析", level: 70 },
    ],

    // Social / contact links
    socials: [
      { label: "GitHub",    url: "https://github.com/yourusername" },
      { label: "Twitter/X", url: "https://twitter.com/yourusername" },
      { label: "Email",     url: "mailto:you@example.com" },
    ]
  }

};


// ── Posts (auto-generated from posts/ folder) ─────────────

window.SITE_DATA.research = [
    {
      id:         "research-3",
      emoji:      "\ud83d\udd2d",
      image:      "",
      date:       "2025-03-15",
      title:      "Deep Learning for Astronomical Image Classification",
      title_zh:   "\u7528\u4e8e\u5929\u6587\u56fe\u50cf\u5206\u7c7b\u7684\u6df1\u5ea6\u5b66\u4e60",
      excerpt:    "An investigation into convolutional neural networks applied to classifying galaxies and nebulae from telescope imagery.",
      excerpt_zh: "\u7814\u7a76\u5c06\u5377\u79ef\u795e\u7ecf\u7f51\u7edc\u5e94\u7528\u4e8e\u4ece\u671b\u8fdc\u955c\u56fe\u50cf\u4e2d\u5206\u7c7b\u661f\u7cfb\u548c\u661f\u4e91\u7684\u65b9\u6cd5\u3002",
      content: `
# Deep Learning for Astronomical Image Classification

## Abstract

This research explores the application of **convolutional neural networks (CNNs)** to classify astronomical objects from telescope imagery, achieving 94.3% accuracy on the benchmark dataset.

## Methodology

We trained a ResNet-50 model on the Galaxy Zoo dataset:

- 270,000 labeled galaxy images
- Data augmentation: rotation, flipping, color jitter
- Transfer learning from ImageNet weights

\`\`\`python
import torch, torchvision
model = torchvision.models.resnet50(pretrained=True)
model.fc = torch.nn.Linear(2048, num_classes)
\`\`\`

## Results

| Model      | Accuracy | F1 Score |
|------------|----------|----------|
| ResNet-50  | 94.3%    | 0.941    |
| VGG-16     | 91.2%    | 0.909    |
| Custom CNN | 87.5%    | 0.872    |

## Conclusion

Deep learning significantly outperforms classical methods for astronomical classification tasks.
  `,
      content_zh: `
# 用于天文图像分类的深度学习

## 摘要

本研究探索将**卷积神经网络（CNN）**应用于从望远镜图像中分类天文对象，在基准数据集上达到了94.3%的准确率。

## 方法论

我们在Galaxy Zoo数据集上训练了ResNet-50模型：

- 270,000张有标签的星系图像
- 数据增强：旋转、翻转、色彩抖动
- 基于ImageNet权重的迁移学习

\`\`\`python
import torch, torchvision
model = torchvision.models.resnet50(pretrained=True)
model.fc = torch.nn.Linear(2048, num_classes)
\`\`\`

## 结果

| 模型      | 准确率 | F1分数 |
|-----------|--------|--------|
| ResNet-50 | 94.3%  | 0.941  |
| VGG-16    | 91.2%  | 0.909  |
| 自定义CNN | 87.5%  | 0.872  |

## 结论

深度学习在天文分类任务中显著优于传统方法。
  `
    }
];

window.SITE_DATA.blogs = [
    {
      id:         "blog-3",
      emoji:      "\ud83d\ude80",
      image:      "",
      date:       "2025-03-20",
      title:      "My Journey Setting Up a Home Observatory",
      title_zh:   "\u6211\u642d\u5efa\u5bb6\u5ead\u5929\u6587\u53f0\u7684\u5386\u7a0b",
      excerpt:    "From a cheap refractor to a motorized equatorial mount \u2014 how I built my backyard observatory step by step.",
      excerpt_zh: "\u4ece\u4e00\u53f0\u5ec9\u4ef7\u6298\u5c04\u671b\u8fdc\u955c\u5230\u7535\u52a8\u8d64\u9053\u4eea\u2014\u2014\u6211\u662f\u5982\u4f55\u4e00\u6b65\u6b65\u642d\u5efa\u540e\u9662\u5929\u6587\u53f0\u7684\u3002",
      content: `
# My Journey Setting Up a Home Observatory

It started with a **$89 refractor telescope** on a wobbly tripod. Three years later, I'm imaging galaxies from my backyard.

## Phase 1: The Humble Beginning

My first night with a real telescope was humbling. I couldn't even find Jupiter.

## Phase 2: Getting Serious

After joining my local astronomy club, I learned:

1. Light pollution maps are essential
2. A goto mount changes everything
3. **Astrophotography** requires patience above all

## Phase 3: The Current Setup

- **OTA**: Explore Scientific 102mm APO
- **Mount**: Sky-Watcher EQ6-R Pro
- **Camera**: ZWO ASI294MC Pro
- **Software**: PixInsight + NINA

Clear skies! 🌟
  `,
      content_zh: `
# 我搭建家庭天文台的历程

一切从一台**89美元的折射望远镜**和一个摇摇晃晃的三脚架开始。三年后，我已经在后院拍摄星系了。

## 第一阶段：谦逊的开始

用真正望远镜的第一个夜晚让我感到谦卑。我甚至找不到木星。

## 第二阶段：认真起来

1. 光污染地图至关重要
2. 自动导向赤道仪改变了一切
3. **天文摄影**最需要的是耐心

## 第三阶段：当前配置

- **镜筒**：Explore Scientific 102mm APO
- **赤道仪**：Sky-Watcher EQ6-R Pro
- **相机**：ZWO ASI294MC Pro
- **软件**：PixInsight + NINA

晴空万里！🌟
  `
    }
];
